apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: mysqldb 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        run: mysqldb 
    spec:
      containers:
      - name: mysqldb 
        image: isaacg9277/stakepoolmysqlv1
        ports:
        - containerPort: 3306
