apiVersion: v1
kind: Service
metadata:
  name: votewallet
  labels:
    run: votewallet
spec:
  ports: 
  - port: 19113
    protocol: TCP
    name: grpc
  - port: 19110
    protocol: TCP 
    name: rpc
  - port: 80
    protocol: TCP
    name: http
  - port: 22
    protocol: TCP
    name: ssh 
  selector:
    run: votewallet 
  type: NodePort 
