apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    run: webserver
spec:
  ports: 
  - port: 80
    protocol: TCP
    name: http 
  - port: 8000
    protocol: TCP 
    name: proxy 
  selector:
    run: webserver  
  type: NodePort





