apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: webserver 
    spec:
      containers:
      - name: webserver
        image: isaacg9277/test:web_v1
        ports:
        - containerPort: 80
