apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    run: mysqldb
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql 
  - port: 8000
    protocol: TCP
    name: proxy 
  selector:
    run: mysqldb 
  type: NodePort
